Update fetch_build

diff --git a/fetch_build b/fetch_build
--- a/fetch_build
+++ b/fetch_build
@@ -1,13 +1,26 @@
 #!/bin/bash
 
-[[ "$EUID" -eq "0" ]] || { sudo -p "Please enter your password to continue: " "$0" "$@"; exit $?; }
+# Check if the script is run as root. If not, prompt for sudo password and rerun the script with sudo.
+if [[ "$EUID" -ne 0 ]]; then
+    sudo -p "Please enter your password to continue: " "$0" "$@"
+    exit $?
+fi
 
+# Exit immediately if a command exits with a non-zero status.
 set -e
 
+# Remove any existing ubuntu.iso file.
 rm -f ubuntu.iso
 
+# Source the configuration file to get the necessary variables.
 source fetch_build.conf
 
-[ -z "$DOWNLOAD_ISO" ] && wget -O ubuntu.iso "https://releases.ubuntu.com/$CODENAME/ubuntu-$RELEASE-desktop-$ARCH.iso" || wget -O ubuntu.iso "$DOWNLOAD_ISO"
+# Download the ISO file. If DOWNLOAD_ISO is not set, construct the URL using CODENAME, RELEASE, and ARCH.
+if [ -z "$DOWNLOAD_ISO" ]; then
+    wget -O ubuntu.iso "https://releases.ubuntu.com/$CODENAME/ubuntu-$RELEASE-desktop-$ARCH.iso"
+else
+    wget -O ubuntu.iso "$DOWNLOAD_ISO"
+fi
 
+# Run the make command to build the project.
 make
